= AI 202: Next-level AI Mastery for Java Developers

== Abstract

In this session, the presenter reviews and builds upon key Generative AI (GenAI) capabilities to show how to incorporate capabilities essential for delivering applications with real-world value.

Concepts covered will include some or all of the following, depending on time available:

* Spring AI and the models it supports
* Types of Messages and how to use them
* LLM responses, Spring AI outputs
* Prompts and PromptTemplates
* Tokens, the building block$ of AI
* Vector stores: unleashing AI on your data
* Conversation memory: 100x your AI's capabilities
* Images from text: can AI draw better than you?
* Deployment considerations for your Spring AI app

Come to this session for a fast-paced, *live-coding adventure* to learn how to put AI to work for you.

== Developer & Presenter

Mark Heckler, MBA is the Senior Director of Field Engineering at Moderne.

He has worked with key players in numerous industries and organizations to develop, deliver, and maintain critical capabilities securely, on time, and on budget. Mark is a Java Champion, open source contributor, author of Spring Boot: Up and Running (https://bit.ly/springbootbook), and a licensed, instrument-rated pilot.