= Build Better, Deploy Faster: Spring Boot + Spring Cloud in the Cloud for frictionless Kubernetes-based Microservices

== Abstract

In this session, you'll learn how to leverage proven patterns & open source software to rapidly build a robust portfolio of microservices that provide a solid foundation for your dynamic and growing microservice architecture, then learn how to make the cloud do it for you so you can focus on your stakeholders' needs. This session addresses vital points such as:

+ Configuration services
+ Microservice registration and discovery
+ Features for system resilience
+ Intelligent routing
+ Secure secret keeping

And more, depending on time available.

The presenter will demonstrate how to develop, deploy, and manage microservices with tools employed by industry leaders to build resilient, scalable, & available systems using Spring Cloud and Azure, but concepts and constructs shown apply to various frameworks and cloud platforms.

== Developer & Presenter

Mark Heckler is a software developer & Principal Cloud Developer Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on Twitter @mkheck.
