= Challenging Conventional Wisdom: A thought-provoking review of "best practices"

== Keynote Abstract

As developers, we want to develop and deploy the best software possible. It's a matter of personal and professional pride! We constantly strive to improve, learning from our personal experience, knowledge shared in the community, and especially from practices declared to be the best for software development. But is this always a good thing?

Far too often, we accept without question a so-called "best practice" simply because it sounds reasonable. But shouldn't we do more than a quick "sniff test" before adopting a new practice within our development team or organization? What if today's best practice becomes tomorrow's code smell or worse, mounting technical debt?

The presenter will examine "best practices" that seem beyond reproach, such as:

* Code comments
* Test coverage
* Monoliths/distributed systems
* Issue tracking
* Native code, VM/GC
* "Move fast & break things"
* Cattle, pets
* Cloud-based IDEs
* Self hosting, public cloud
* JSON, XML

Best practice, in or out? Whatever you decide, you'll know why. Challenge everything! (Except for that last statement, perhaps)

== Additional Information

This session is designed to challenge conventional wisdom and encourage all attendees to think for themselves.

== Developer & Presenter

Mark Heckler is a software developer & Principal Cloud Developer Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on Twitter @mkheck.
