= Cloud Native Java: To Infinity and Beyond!

== Abstract

In this session, learn how to use proven patterns & open source software to rapidly develop a resilient, production-ready microservice architecture. This session addresses vital points such as:

* Configuration services
* Microservice registration and discovery
* Circuit breakers for graceful degradation
* Load balancing and intelligent routing
* Asynchronous messaging
* Reactive services, events, & backpressure
* Functional reactive routing/API creation

The presenter will demonstrate how to develop & effectively manage microservices using OSS tools like Spring Boot, Spring Cloud, & Netflix OSS. Come to this session and go Cloud Native!

== Developer & Presenter

Mark Heckler is a Pivotal Principal Technologist & Spring Developer Advocate, conference speaker, published author, & Java Champion focusing upon developing innovative production-ready software at velocity for the Cloud and IoT applications. He has worked with key players in the manufacturing, retail, medical, scientific, telecom, and financial industries and various public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author/curator of a developer-focused blog (https://www.thehecklers.com[Hecklers in Development, brewing stronger Java]) and an occasionally interesting Twitter account (https://twitter.com/mkheck[@mkheck]).
