= Cloud Native Java: To Infinity and Beyond!

== Abstract

In this session, learn how to use proven patterns & open source software to rapidly develop a resilient, production-ready microservice architecture. This session addresses vital points such as:

* Configuration services
* Microservice registration and discovery
* Circuit breakers for graceful degradation
* Load balancing and intelligent routing
* Asynchronous messaging
* Reactive services, events, & backpressure
* Functional reactive routing/API creation

The presenter will demonstrate how to develop & effectively manage microservices using OSS tools like Spring Boot, Spring Cloud, & Netflix OSS. Come to this session and go Cloud Native!

== Developer & Presenter

Mark Heckler is a software developer & Cloud Developer Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on Twitter @mkheck.
