= This stuff is cool, but HOW CAN I GET MY COMPANY TO DO IT??!

== Abstract

Cloud Native, containers, Kubernetes, microservices, and more: we go to conferences and get excited about the potential of so many things that could revolutionize our development and change our organizational and professional lives! And then, we go home...and hit the wall. If you've ever asked yourself, "This stuff is cool, but HOW CAN I GET MY COMPANY TO DO IT??!", this is the session for you.

Learn from an experienced software developer (who also happens to have an MBA) how to make your case to leadership, presenting management-ready justifications for changes in "your world" that will positively impact the business as a whole. Topics include:

* How would this change affect your organization's/group's/team's work?
* How would this change impact (positively and negatively) your tech stack (internal considerations)?
* How would this change contribute to recruitment/retention (external considerations)?
* Seeing beyond your borders: how could this change positively - and negatively - affect the business?
* Putting numbers with it: pros, cons, and caveats

Come to this session to dramatically boost your chances of making an actual, positive change to your organization!

== Additional Information

Most of us participate in conferences to learn how to do more, and better, for our organizations...and to improve our organizations as well. But many times, we are out in front of our organizations trying to pull them along to better things! This can be incredibly difficult to do if we aren't speaking the same language as our leadership.

The presenter will share several key components of cutting-edge software development and tie them to business measurements, provide meaningful and compelling examples, and show you how to apply straightforward financial formulas to software-defined concepts to improve your decisions, work environment, business cases, and ultimately, your company's chance to survive and thrive.

== Developer & Presenter

Mark Heckler is a software developer & Principal Cloud Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on Twitter @mkheck.
