= Copilot is my Copilot: Pair programming with an AI

== Abstract

What if you could develop better apps faster? What if you had a pair programming partner who could help you write cleaner code, catch bugs, and even write some code and tests for you, whenever you wanted or needed to do so?

GitHub Copilot is an Artificial Intelligence (AI) code completion tool that can help you write better code faster. It's not a replacement for your hard-won expertise, but it can provide timely assistance. Copilot offers code and test suggestions without judgement, letting you evaluate and consider - then use or discard - logic for inclusion that complements your existing code and style choices. Why overflow your stack when you can use a trained professional?

Come to this session to learn -- from a software developer and licensed pilot -- how to level up your development process using Copilot!

== Developer & Presenter

Mark Heckler, MBA is the Senior Director of Field Engineering at Moderne.

He has worked with key players in numerous industries and organizations to develop, deliver, and maintain critical capabilities securely, on time, and on budget. Mark is a Java Champion, open source contributor, author of Spring Boot: Up and Running (https://bit.ly/springbootbook), and a licensed, instrument-rated pilot.