= Das Boot: Diving into Debugging Spring Boot Applications

== Abstract

Spring Boot streamlines Java and Kotlin development with its developer-first focus. By simplifying dependency management and deployment, providing unmatched autoconfiguration capabilities, and leveraging convention over configuration at every opportunity, developers can focus nearly all of their efforts on designing, developing, and delivering amazing software. This is the happy path, and it is wide.

Good developers write good code, but great developers can diagnose the inevitable issues that arise in complex software systems. When your code takes the road less traveled, how can you quickly identify, isolate, and resolve the problem, not the symptoms? How can you move from good to great?

In this session, the presenter will take you on a live-coding adventure(TM) into the hidden passageways of your Spring Boot application. Topics covered may include (but are not limited to) the following, depending upon time available:

* Application startup, including autoconfiguration steps/process
* Bean initialization and configuration
* Debugging local apps via IDE
* Remote debugging container applications
* Tracing distributed apps
* Debugging reactive code

Come to this session to get a deeper understanding of your Spring Boot apps and level up your debugging skills!

== Additional Information

This session is meant to provide an approachable introduction to "find and fix" challenges when Spring Boot apps don't work as intended/desired. Some advanced topics will be covered, but I provide ample narrative throughout to ensure no one is left behind.

== Developer & Presenter

Mark Heckler is a software developer & Principal Cloud Developer Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on Twitter @mkheck.
