= Full-stack Reactive Kotlin with Project Reactor & Spring Boot 2

== Abstract

Reactive programming offers Java & Kotlin developers a way to build message-driven, elastic, resilient, and responsive services...yet many developers don't know where to begin. The Reactive Streams initiative provides a baseline and Project Reactor provides a great way to become immediately productive, leveraging reactive capabilities from end to end. Whether you're coming from a Spring MVC environment or a functional perspective, Reactor empowers you to spin up fully reactive Spring Boot 2 applications quickly and efficiently.

In this talk, the presenter dives into the net-new Netty-based web runtime and shows you how to:

* integrate easily with existing Spring-stack technologies
* easily transition from blocking to reactive applications & systems
* define your API in an imperative style *and* functionally, reaping all benefits both ways
* leverage powerful new testing mechanisms to make code better and life easier

_The presenter will code all examples live and in real time_. This is not an abstract discussion, come to gain real, practical knowledge!

== Developer & Presenter

Mark Heckler is a Professional Problem Solver and Spring Developer & Advocate at Pivotal, conference speaker, published author, & Java Champion focusing upon developing innovative production-ready software at velocity for the Cloud. He has worked with key players in the manufacturing, retail, medical, scientific, telecom, and financial industries and various public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author/curator of a developer-focused blog (https://www.thehecklers.com) and an occasionally interesting Twitter account (@mkheck).
