= Give Kotlin the Boot? Pros & cons of using Kotlin vs. Java with Spring Boot

== Abstract

In addition to Java, developers can use Kotlin to create Spring Boot applications. But should they? What advantages does Kotlin offer over Java? What are the downsides?

Life is filled with tradeoffs, and choices are good to have. But life is better when you know the tradeoffs *before* making important decisions, and this session is built around sharing and showing some of those. As both a Java Champion and Kotlin Developer Expert, the presenter loves both children equally, but not in the same ways. Come to this session to see several places in which your choice of language could result in either promise or pitfall.  All examples will be coded *live & in real-time*!

== Developer & Presenter

Mark Heckler is a software developer & Cloud Developer Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on Twitter @mkheck.
