= Hailing Frequencies Open: A Live Coding Adventure in Interservice Comms

== Abstract

As all aspects of our lives become more distributed and the world gets ever smaller - we can "Zoom" anywhere in milliseconds! - systems that support tasks large and small become more interconnected as well. Distributed systems are the future, and anyone who says otherwise is probably selling monoliths.

With the number of applications and cloud regions expanding at a dizzying rate, communication is key. In this session, the presenter leads attendees on a live-coding adventure exploring various options for your critical interservice comms. Topics covered depend on time available, but may include:

* HTTP-based interactions, e.g. REST APIs using standard types
* HTTP-based interactions using Reactive Streams publishers
* Server Sent Events
* WebSocket
* RSocket
* Message-based interactions using messaging platforms, e.g. RabbitMQ, Kafka

All examples will be coded *live & in real-time*. Hailing frequencies open, Captain!

== Developer & Presenter

Mark Heckler is a software developer & Cloud Developer Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on Twitter @mkheck.
