= Spring Boot desde cero

== Sumario

En esta charla, recibirán una breve introducción a los conceptos claves de Spring Boot y además aprenderán cómo construir rápidamente aplicaciones funcionales. Los temas incluyen:

* Los tres características centrales de Spring Boot
* ¿Maven o Gradle? ¿Java o Kotlin? ¿Cuál versión de Boot debes usar? ¿Por qué?
* Empezar a construir aplicaciones de Spring Boot
* Soporte para Spring en los Integrated Development Environments (IDEs)
* ¡Hola mundo! Crear tu primera API REST en Spring Boot
* Añadir el aceso de bases de datos a tu aplicaciones de Spring Boot

Y cualquier cosa que podamos incluir en la sesión. Ven a ver de qué se trata toda la emoción, *¡todo el código se escribirá en vivo y en tiempo real!*

== Bio

Mark Heckler es Principal Technologist y Spring Developer Advocate, ponente, autor, y Campeón de Java centrándose en desarrollo de software para el Internet of Things (IoT) y la nube. Ha trabajado con negocios claves en los campos de fabricación, retail, médico, científico, telecomunicación, y finanzas y también varios organizaciones públicas para desarrollar y entregar habilidades críticas con puntualidad y dentro de presupuesto. Mark es contribuidor de código abierto y autor/curador de un blog para desarrolladores (http://www.losheckler.com) y una cuenta ocasionalmente interesante en Twitter (https://twitter.com/mkheck[@mkheck]). También es el creador y único curador de Spring Noticias en español (https://springnoticias.io, https://twitter.com/springnoticias), la fuente de todas las noticias más importantes para desarrolladores de Spring y Java/Kotlin.
