= Zero to Spring Boot in 50 Minutes

== Abstract

In this session, you'll get a quick introduction to the critical concepts of Spring Boot and learn how to quickly build working Spring Boot applications. Topics include:

* The three core features of Spring Boot upon which everything else builds
* Maven or Gradle? Java or Kotlin? Which version of Boot should you use? Why?
* Getting started creating Spring Boot apps
* Spring support in Integrated Development Environments (IDEs)
* Hello world! Creating your first Spring Boot REST API
* Adding database access to your Spring Boot app

And anything else we can fit into the session. Come & see what the excitement is all about, *all code will be written live and in real-time!*

== Developer & Presenter

Mark Heckler is a Professional Problem Solver and Spring Developer & Advocate at VMware, conference speaker, published author, & Java Champion focusing upon developing innovative production-ready software at velocity for the Cloud. He has worked with key players in the manufacturing, retail, medical, scientific, telecom, and financial industries and various public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author/curator of a developer-focused blog (https://www.thehecklers.com) and an occasionally interesting Twitter account (@mkheck).
