= Making the long road short: How to migrate legacy enterprise Java apps to Spring Boot

== Abstract

Java EE (now Jakarta EE) is a well-established standard for creating enterprise Java applications and powers many critical applications with long lifespans. A frequent question is this: how can I gain access to the power of Spring & Spring Boot to take advantage of their dependency management, CDI, ease of data/streams use & integration, reactive programming, first-class Kotlin support, or any of a number of other capabilities? What are preferred migration patterns to smooth the path?

In this session, the presenter demonstrates how to transform legacy Java EE applications to Spring Boot, live and in real-time. This is not a theoretical discussion or a smackdown, it's a live-coding journey from one stack to another for those who need to know. Come see how to level up on Spring Boot!

== Developer & Presenter

Mark Heckler is a Pivotal Principal Technologist & Spring Developer Advocate, conference speaker, published author, & Java Champion focusing upon developing innovative production-ready software at velocity for the Cloud and IoT applications. He has worked with key players in the manufacturing, retail, medical, scientific, telecom, and financial industries and various public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author/curator of a developer-focused blog (http://www.thehecklers.com[Hecklers in Development, brewing stronger Java]) and an occasionally interesting Twitter account (https://twitter.com/MkHeck[@mkheck]).
