= Paving a Painless Path to Production AI in your Java Applications

== Abstract

Artificial Intelligence is eating the world, and new and amazing use cases are being discovered every day. These uses for AI aren't just in new domains, but perhaps even more importantly, in areas that are broadly applicable in countless "everyday" mission-critical applications.

This places developers in a difficult position: how do you take advantage of these new capabilities without significant investments in both time and tooling to become an AI expert? How do you plug AI into your existing applications without massive rearchitecting and rewriting?

Come to this session for a dive-into-the-deep-end introduction of key concepts and tools at your disposal and even better, a *live-coding adventure* using Spring Boot, Java, and Azure OpenAI. You'll leave this session with the knowledge and confidence to pave a painless (and powerful) path to production AI in your Java applications.

== Developer & Presenter

Mark Heckler is a software developer & Principal Cloud Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on X @mkheck.
