= Go Reactive with your Data: How to stop blockages using Spring Data & Reactive NoSQL DBs

== Abstract

Reactive programming is a great tool for the skilled developer, enabling us to deliver more scalable, resilient, & responsive services...but only if we leverage the reactive model throughout the entire stack! Failing to (re)design our systems to leverage fully reactive data storage & retrieval can both increase complexity *and* degrade performance.

Using Spring Data and your favorite NoSQL data store, you can exploit the full power of reactive systems, all the way to the metal. In this session, the presenter discusses & compares reactive support for MongoDB, Cassandra, Couchbase, & Redis, then demonstrates how to put each of them into production by *live coding* real-world examples. Come to this session to level up and block no more!

== Developer & Presenter

Mark Heckler is a Professional Problem Solver and Spring Developer & Advocate at Pivotal, conference speaker, published author, & Java Champion focusing upon developing innovative production-ready software at velocity for the Cloud. He has worked with key players in the manufacturing, retail, medical, scientific, telecom, and financial industries and various public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author/curator of a developer-focused blog (https://www.thehecklers.com) and an occasionally interesting Twitter account (@mkheck).
