= Current Abstracts for sessions, deep dives, & workshops I can deliver upon request

== Maintainer

* Mark Heckler
* mailto:mark@thehecklers.com[mark@thehecklers.com]
* mailto:mark@thehecklers.org[mark@thehecklers.org]
* mailto:mark@losheckler.com[mark@losheckler.com]
* mailto:mark.heckler@gmail.com[mark.heckler@gmail.com]
* https://twitter.com/mkheck[@mkheck on Twitter]

== Purpose

This repository contains abstracts for talks I am currently delivering in one or more of the following formats:

* Conference/meetup sessions ranging from 50 to 90 minutes
* Deep dives ranging from 2 to 3 hours

== Document formats

Each abstract is provided in two formats:

* Plain text (.adoc extension), viewable in any text editor
* HTML format (.html extension), viewable in any web browser

== Notes

I can present in either English or Spanish. Talks I give in Spanish are indicated with "_ES" in their titles.

Puedo presentar en inglés o español. Las presentaciones disponible en español se indican con "_ES" en los títulos.

== Bio

=== English

Mark Heckler is a software developer & Principal Cloud Developer Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on Twitter @mkheck.

=== Español

Mark Heckler es desarrollador de software y Cloud Developer Advocate de Java/Idiomas de JVM en Microsoft, ponente, Java Champion, y Kotlin Developer Expert enfocado en el desarrollo rápido de software "production-ready" para la nube y el Internet of Things (IoT). Ha trabajado con negocios claves en numerosas industrias y organizaciones del sectór público para desarrollar y entregar habilidades críticas con puntualidad y dentro de presupuesto. Mark es contribuidor de código abierto y autor/curador de un blog para desarrolladores (http://www.losheckler.com[Los Heckler en desarrollo, haciendo Java más fuerte]) y una cuenta ocasionalmente interesante en Twitter (https://twitter.com/mkheck[@mkheck]).

== Photo

https://1drv.ms/u/s!Asa7U7j7HrpThtkXK0VK3muwW42E5A[Click here to view/download current photo]

== Contacting me

* https://www.thehecklers.com[Hecklers in Development, brewing stronger Java (personal website)]
* mailto:mark@thehecklers.com[Email me @ mark@thehecklers.com]
* mailto:mark@losheckler.com[Enviarme un email en mark@losheckler.com]