= Current Abstracts for sessions, deep dives, & workshops I can deliver upon request

== Maintainer

* Mark Heckler
* mailto:mark@thehecklers.com[mark@thehecklers.com]
* mailto:mark@thehecklers.org[mark@thehecklers.org]
* https://twitter.com/MkHeck[@mkheck on Twitter]

== Purpose

This repository contains abstracts for talks I am currently delivering in one or more of the following formats:

* Conference/meetup sessions ranging from 50 to 90 minutes
* Deep dives ranging from 2 to 3 hours

== Document formats

Each abstract is provided in two formats:

* Plain text (.adoc extension), viewable in any text editor
* HTML format (.html extension), viewable in any web browser

== Notes

I can present in either English or Spanish. Talks I give in Spanish are indicated with "_ES" in their titles.

Puedo presentar en inglés o español. Las presentaciones disponible en español se indican con "_ES" en los títulos.

== Bio

=== English

Mark Heckler is a Pivotal Principal Technologist & Spring Developer Advocate, conference speaker, published author, & Java Champion focusing upon developing innovative production-ready software at velocity for the Cloud and IoT applications. He has worked with key players in the manufacturing, retail, medical, scientific, telecom, and financial industries and various public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author/curator of a developer-focused blog (https://www.thehecklers.com) and an occasionally interesting Twitter account (@mkheck).

=== Español

Mark Heckler es Principal Technologist y Spring Developer Advocate, presentador, y autor centrándose en desarrollo de software para el Internet of Things (IoT) y la nube. Ha trabajado con negocios claves en los campos de fabricación, retail, médico, científico, telecomunicación, y finanzas y también varios organizaciones públicas para desarrollar y entregar habilidades críticas con puntualidad y dentro de presupuesto. Mark es contribuidor de código abierto y autor/curador de un blog para desarrolladores (http://www.thehecklers.com) y una cuenta ocasionalmente interesante en Twitter (@mkheck).

== Photo

https://drive.google.com/open?id=1WuQe9DLbS4zjLtqEXm-LQvqoBkf1gA4Q[Click here to download current photo]

== Contacting me

* https://www.thehecklers.com[Hecklers in Development, brewing stronger Java (personal website)]
* mailto:mark@thehecklers.com[Email me @ mark@thehecklers.com]
