= Current Abstracts for keynotes, sessions, deep dives, & workshops I can deliver upon request

== Maintainer

* Mark Heckler
* mailto:mark@thehecklers.com[mark@thehecklers.com]
* mailto:mark@thehecklers.org[mark@thehecklers.org]
* mailto:mark.heckler@gmail.com[mark.heckler@gmail.com]
* https://x.com/mkheck[@mkheck on X]
* https://bsky.app/profile/mkheck.bsky.social[@mkheck on Bluesky]
* https://mastodon.cloud/@mkheck[@mkheck on Mastodon]

== Purpose

This repository contains abstracts for talks I am currently delivering in one or more of the following formats:

* Keynotes
* Conference/meetup sessions ranging from 50 to 90 minutes
* Deep dives ranging from 2 to 3 hours

== Document formats

Each abstract is provided in two formats:

* Plain text (.adoc extension), viewable in any text editor
* HTML format (.html extension), viewable in any web browser

== Notes

I can present in either English or Spanish. Talks I give in Spanish are indicated with "_ES" in their titles.

Puedo presentar en inglés o español. Las presentaciones disponible en español se indican con "_ES" en los títulos.

== Bio

=== English

Mark Heckler, MBA is the Senior Director of Field Engineering at Moderne.

He has worked with key players in numerous industries and organizations to develop, deliver, and maintain critical capabilities securely, on time, and on budget. Mark is a Java Champion, open source contributor, author of Spring Boot: Up and Running (https://bit.ly/springbootbook), and a licensed, instrument-rated pilot.

=== Español

Mark Heckler, MBA, es Director Sénior de Ingeniería de Campo en Moderne.

Ha colaborado con actores clave de diversos sectores y organizaciones para desarrollar, entregar y mantener capacidades críticas de manera segura, puntual y dentro del presupuesto. Mark es Java Champion, colaborador de código abierto, autor de Spring Boot: Up and Running (https://bit.ly/springbootbook) y piloto con licencia y habilitación para vuelo por instrumentos.

== Photo

https://1drv.ms/u/s!Asa7U7j7HrpThtkXK0VK3muwW42E5A[Click here to view/download current photo]

== Contacting me

* https://www.thehecklers.com[Hecklers in Development, brewing stronger Java (personal website)]
* mailto:mark@thehecklers.com[Email me / envíame un email @ mark@thehecklers.com]
