= RSocket Wrench: Hand me that Spanner!

== Abstract

You may (or may not) have heard of RSocket, the flexible and resilient way to crank up microservice scalability. This session offers a quick introduction, but that isn't its primary mission; rather, this is an hour-long (more or less) meandering in which Mark explores various scenarios with Spring Boot, Reactor, and RSocket to see what combinations might work, what might not, and where an edge or two may lie.

Success is not guaranteed, come join the fun! All examples will be coded *live & in real-time*.

== Developer & Presenter

Mark Heckler is a Professional Problem Solver and Spring Developer & Advocate at VMware, conference speaker, published author, & Java Champion focusing upon developing innovative production-ready software at velocity for the Cloud. He has worked with key players in the manufacturing, retail, medical, scientific, telecom, and financial industries and various public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author/curator of a developer-focused blog (https://www.thehecklers.com) and an occasionally interesting Twitter account (@mkheck).
