= RSocket + Spring : A Full Throttle Introduction

== Abstract

You've evolved from monolith to microservices, from blocking code to reactive, all in pursuit of better scaling and resource maximization. And you're _so close_! How do you cross the final frontier - the network boundary - and wring out the ultimate in system performance, flexibility, and resilience...and _system-wide_ scalability?

Enter RSocket, a transport-independent binary protocol from performance-obsessed industry and individual contributors. Building upon the reactive streams paradigm and Project Reactor, RSocket knocks down the (network) walls separating your microservices and enables you to truly treat them as a fully-interconnected system while providing mechanisms that increase flexibility and resilience instead of reducing it.

RSocket has four interaction models to support all the use cases:

* request/response
* request/stream
* fire & forget
* channel (bi-directional stream)

Combining Spring Boot with RSocket gives you the fastest, most developer-friendly way to explore and exploit your reactive superpowers. Come to this session for a full throttle, live-coding adventure introducing Spring Boot RSocket mechanisms & models and showing how to put them to work for you. All examples will be coded *live & in real-time*!

== Developer & Presenter

Mark Heckler is a Professional Problem Solver and Spring Developer & Advocate at VMware, conference speaker, published author, & Java Champion focusing upon developing innovative production-ready software at velocity for the Cloud. He has worked with key players in the manufacturing, retail, medical, scientific, telecom, and financial industries and various public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author/curator of a developer-focused blog (https://www.thehecklers.com) and an occasionally interesting Twitter account (@mkheck).
