= Services Assemble! Aplicar principios MVP para crear Microservicios Sin Caos con Spring Cloud/Netflix OSS

== Sumario

En esta sesión, aprender como usar modelos probado y software de código abierto para construir rápidamente un portfolio robusto de microservicios que provean una base sólida para una arquitectura dinámica y creciente. Esta sesión discute puntos claves como:

* Servicios de configuración
* Registro y descubrimiento de microservicios
* Cortacircuitos para degradación gradual
* Balanceo de carga y enrutamiento inteligente
* Mensajería asíncrona
* Servicios reactivos, eventos, y contrapresión

El orador mostrará como desarrollar y manejar efectivamente microservicios con herramientas de código abierto usado por Netflix para ayudar la entrega de pelis globalmente 24x7.

== Bio

Mark Heckler es Principal Technologist y Spring Developer Advocate, presentador, y autor centrándose en desarrollo de software para el Internet of Things (IoT) y la nube. Ha trabajado con negocios claves en los campos de fabricación, retail, médico, científico, telecomunicación, y finanzas y también varios organizaciones públicas para desarrollar y entregar habilidades críticas con puntualidad y dentro de presupuesto. Mark es contribuidor de código abierto y autor/curador de un blog para desarrolladores (http://www.thehecklers.com) y una cuenta ocasionalmente interesante en Twitter (@mkheck).
