= Springing en Kotlin: Cómo hacer que la magia sea aún más mágica

== Sumario

Desarollar applicaciones con Spring Boot ya es una experiencia tan mágica, pero es posible mejorarla? Puede aumentarse la mágia?

En esta sesión, examinamos como Kotlin se puede utilizar para reducir repetición, aumentar calidad, y elevar la brujería de tu código. El presentador demostrará como empezar con Kotlin en tus applicaciones de Spring actuales y, después de empieza tu viaje, como lo puedes continues. Ven a esta sesión para "elevar tu nivel" en Spring+Kotlin! (Batas son opcionales)

== Bio

Mark Heckler es desarrollador de software y Principal Cloud Developer Advocate de Java/Idiomas de JVM en Microsoft, ponente, Java Champion, y Kotlin Developer Expert enfocado en el desarrollo rápido de software "production-ready" para la nube y el Internet of Things (IoT). Ha trabajado con negocios claves en numerosas industrias y organizaciones del sectór público para desarrollar y entregar habilidades críticas con puntualidad y dentro de presupuesto. Mark es contribuidor de código abierto y autor/curador de un blog para desarrolladores (http://www.losheckler.com[Los Heckler en desarrollo, haciendo Java más fuerte]) y una cuenta ocasionalmente interesante en Twitter (https://twitter.com/mkheck[@mkheck]).
