= Springing en Kotlin: Cómo hacer que la magia sea aún más mágica

== Sumario

Desarollar applicaciones con Spring Boot ya es una experiencia tan mágica, pero es posible mejorarla? Puede aumentarse la mágia?

En esta sesión, examinamos como Kotlin se puede utilizar para reducir repetición, aumentar calidad, y elevar la brujería de tu código. El presentador demostrará como empezar con Kotlin en tus applicaciones de Spring actuales y, después de empieza tu viaje, como lo puedes continues. Ven a esta sesión para "elevar tu nivel" en Spring+Kotlin! (Batas son opcionales)

== Bio

Mark Heckler es Principal Technologist y Spring Developer Advocate, presentador, y autor centrándose en desarrollo de software para el Internet of Things (IoT) y la nube. Ha trabajado con negocios claves en los campos de fabricación, retail, médico, científico, telecomunicación, y finanzas y también varios organizaciones públicas para desarrollar y entregar habilidades críticas con puntualidad y dentro de presupuesto. Mark es contribuidor de código abierto y autor/curador de un blog para desarrolladores (https://www.thehecklers.com) y una cuenta ocasionalmente interesante en Twitter (@mkheck).
