= Springing into Kotlin: How to Make the Magic even more Magical

== Abstract

Developing applications with Spring Boot is already a pretty magical experience, but could it be better? Can the magic get any more powerful than it already is?

Since Spring Framework 5.0 became generally available in 2017, Kotlin has enjoyed *full first class support* as a language for developing Spring applications. As such, you can use Kotlin anywhere you would use Java: migrating to it gradually or all at once, running Spring apps in production with any mix of Java & Kotlin code - including in the same microservice! For Java developers, Kotlin feels like a natural addition to their spellbook. But as with any new endeavor, the first step is often the most difficult to take.

In this talk, we'll look at how Kotlin can be used to reduce boilerplate, increase code quality, and elevate your code wizardry. The presenter will demonstrate how to begin incorporating Kotlin into your existing Spring applications and, once you start your journey, where it can lead. Come to this session to level up on Spring+Kotlin! (Robes optional)

== Developer & Presenter

Mark Heckler is a software developer & Cloud Developer Advocate for Java/JVM Languages at Microsoft, conference speaker, Java Champion, and Kotlin Developer Expert focused on developing innovative production-ready software at velocity for cloud and edge computing platforms. He has worked with key players in numerous industries and public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author of Spring Boot: Up and Running (https://bit.ly/springbootbook) and can be found on Twitter @mkheck.
