= Demystifying Spring Security with Kotlin: A quick introduction for the terminally insecure

== Abstract

No one wants to be the next Equifax (or Target or Yahoo or TGX or Marriott or or or) and feature prominently in headlines of the latest terrible security breach. Often referred to as a Career Limiting Move (CLM), it can also make you and your organization a target for lawsuits, prosecution, and recognition of the worst kind. But security is *hard*, right? Where does one even begin???

One _fully open-source_ solution for application security is widely used and respected: Spring Security. Built with Java & Spring, it provides a proven app security platform that integrates with numerous languages and components to provide end-to-end security for your critical applications. Using the JavaScript framework du jour for front end development? Reactive systems? LDAP? OAuth2/OpenID Connect? *It's in there.*

Since v5 of Spring Framework & v2 of Spring Boot were released in 2017, Kotlin has enjoyed _first class language support_ for all Spring apps, giving you full and unfettered access to the power of Spring Security to protect your critical applications.

Defense is a multi-faceted topic, but your application's security is central to it all. Come to this session for a a live-coding "lock it down" exploration of how to secure your apps now and maintain their security over time using 100% open source software.

== Developer & Presenter

Mark Heckler is a Professional Problem Solver and Spring Developer & Advocate at VMware, conference speaker, published author, & Java Champion focusing upon developing innovative production-ready software at velocity for the Cloud. He has worked with key players in the manufacturing, retail, medical, scientific, telecom, and financial industries and various public sector organizations to develop and deliver critical capabilities on time and on budget. Mark is an open source contributor and author/curator of a developer-focused blog (https://www.thehecklers.com) and an occasionally interesting Twitter account (@mkheck).
