= Bebiendo del Stream: Como usar las plataformas de mensajería para escalamiento y rendimiento

== Sumario

Casi todos de los sistemas de misión crítica tienen elementos distribuidos o son totalmente distribuidos, resultando en numerosos retos: rendimiento, escalamiento, confiabilidad, elasticidad...los ocho mitos del cómputo distribuido son vivos y bienes!

Con frecuencia las plataformas de mensajería se usan para resolver estos problemas y aumentar las capacidades, pero no vienen sin complejidad por si mismas. Ven a esta sesión para aprender como incorporar soluciones de código abierto como Spring Cloud Stream, RabbitMQ, y Apache Kafka para maximizar las capacidades de tus sistemas distribuidos con complejidad mínima. Todos los ejemplos se escribirán en código *en vivo y en tiempo real*!

== Bio

Mark Heckler es desarrollador de software y Principal Cloud Developer Advocate de Java/Idiomas de JVM en Microsoft, ponente, Java Champion, y Kotlin Developer Expert enfocado en el desarrollo rápido de software "production-ready" para la nube y el Internet of Things (IoT). Ha trabajado con negocios claves en numerosas industrias y organizaciones del sectór público para desarrollar y entregar habilidades críticas con puntualidad y dentro de presupuesto. Mark es contribuidor de código abierto y autor/curador de un blog para desarrolladores (http://www.losheckler.com[Los Heckler en desarrollo, haciendo Java más fuerte]) y una cuenta ocasionalmente interesante en Twitter (https://twitter.com/mkheck[@mkheck]).
