= Beber del Corriente: Como usar las plataformas mensajeras para escalamiento y rendimiento

== Sumario

Casi todos de los sistemas de misión crítica tienen elementos distribuidos o son totalmente distribuido, que resulten en retos numerosos: rendimiento, escalamiento, confiabilidad, elasticidad...las ocho falacias de la computación distribuida son vivas y bienes!

Con frecuencia las plataformas mensajeras se usan para resolver estos problemas y aumentar las "ilidades", pero no vienen sin complejidades si mismas. Vengas a esta sesión para aprender como incorporar soluciones de código abierto como Spring Cloud Stream, RabbitMQ, y Apache Kafka para maximizar las capabilidades de tus sistemas distribuidos con complejidad mínima. Todos los ejemplos se escribirán en código *en vivo y en tiempo real*!

== Bio

Mark Heckler es Principal Technologist y Spring Developer Advocate, ponente, y autor centrándose en desarrollo de software para el Internet of Things (IoT) y la nube. Ha trabajado con negocios claves en los campos de fabricación, retail, médico, científico, telecomunicación, y finanzas y también varios organizaciones públicas para desarrollar y entregar habilidades críticas con puntualidad y dentro de presupuesto. Mark es contribuidor de código abierto y autor/curador de un blog para desarrolladores (https://www.losheckler.com) y una cuenta ocasionalmente interesante en Twitter (https://twitter.com/MkHeck[@mkheck]).
