= Beber del Corriente: Como usar las plataformas de mensajería para escalamiento y rendimiento

== Sumario

Casi todos de los sistemas de misión crítica tienen elementos distribuidos o son totalmente distribuidos, resultando en numerosos retos: rendimiento, escalamiento, confiabilidad, elasticidad...los ocho mitos del cómputo distribuido son vivos y bienes!

Con frecuencia las plataformas de mensajería se usan para resolver estos problemas y aumentar las "ilidades", pero no vienen sin complejidad por si mismas. Ven a esta sesión para aprender como incorporar soluciones de código abierto como Spring Cloud Stream, RabbitMQ, y Apache Kafka para maximizar las capabilidades de tus sistemas distribuidos con complejidad mínima. Todos los ejemplos se escribirán en código *en vivo y en tiempo real*!

== Bio

Mark Heckler es Principal Technologist y Spring Developer Advocate, ponente, y autor centrándose en desarrollo de software para el Internet of Things (IoT) y la nube. Ha trabajado con negocios claves en los campos de fabricación, retail, médico, científico, telecomunicación, y finanzas y también varios organizaciones públicas para desarrollar y entregar habilidades críticas con puntualidad y dentro de presupuesto. Mark es contribuidor de código abierto y autor/curador de un blog para desarrolladores (http://www.losheckler.com) y una cuenta ocasionalmente interesante en Twitter (https://twitter.com/mkheck[@mkheck]).
